application: galobarna-87
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /app
  static_dir: app

- url: /.*
  script: _go_app