application: galobarna-87
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: front/dist/index.html
  upload: front/dist/index.html

- url: /app
  static_dir: front/dist

- url: /.*
  script: _go_app

skip_files:
- front/node_modules
- front/src
- front/gulpfile.js
- .git
- ressources
- .gitignore
